kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "parksmap-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/berrutig/adv_dev_homework_template"
      ref: "master"
  strategy:
    jenkinsPipelineStrategy:
       jenkinsfilePath: ParksMap/Jenkinsfile
